
#define Y_VAL_MAPS 50
#define X_VAL_MAPS 75

static const char maps[][Y_VAL_MAPS][X_VAL_MAPS] = {

    {"S    P",
     "XXXXXX"},
    
    {"   P",
     "    ",
     "   X",
     "   X",
     "   X",
     "S  X",
     "XXXX"},
    
    
    {"S  D  P",
     "XXXXXXX",},
    
    
    {"S        P",
     "XX     XX",
     "    B    "},
    
    {"          P",
     "           ",
     "    XXXXXXX",
     "           ",
     "           ",
     "    X      ",
     "           ",
     "           ",
     "           ",
     "       X   ",
     "           ",
     "           ",
     "           ",
     "    X      ",
     "           ",
     "           ",
     "S          ",
     "XXXXXXXXXXX",},

    {" P DDDDDDDDDD                                        ",
     "   D   DD   DD                                       ",
     "   D   DD   DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
     "                                                     ",
     " B   X    X                                          ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                    X   X   X  X  X  ",
     "                      XXXXXXX   B                    ",
     "             B   XXXDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD   ",
     "  B    B                                         D  X",
     "                                                 D  X",
     "                                                 D  X",
     "                                    XXXXXXXXXXXX D  X",
     "                                                 D  X",
     "     S    DDDD               D  D BDDDDD         D  X",
     "     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX",
     "                X                                   X",
     "                X                                   X",
     "                X                                   X",
     "                X                                  DX",
     "XXXXXXXXXXXXXXXXX                       XXXXXXXXXXXXX"},
    
    {"                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                                                     ",
     "                  XXXXXXX                            ",
     "                               S                     ",
     "                             XXXXXX                  ",
     "DDDDDD DDDDDDDDDDDDDDDDDDDDDDD                       ",
     "X                                                    ",
     "X                                                    ",
     "X                                                    ",
     "X                                                    ",   
     "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXDDDDDDDDDDDDDDDDDDDDD"},
    
    
    
    {"S",
     "X"}
};
